### ISSUE TITLE
نمایش لیست

### ISSUE THREAD

**Issue by mort3za** [ctyar/meetups#2]
چطور میشه لیست رو توی براوزر دید؟

اگر نمیشه پیشنهاد میکنم که منتقل بشه روی گیتهاب‌پیجز :)

**Comment by ctyar** [comment]
http://ctyar.github.io/meetups/
فکر کنم باید بزارم تو readme

**Comment by mort3za** [comment]
آها. یه جایی برای گذاشتن لینک هست کنار توضیحات. ریدمی هم داشته باشه که بهتر

**Comment by ctyar** [comment]
Done
